// <auto-generated />
using System;
using System.Collections.Generic;
using AppG1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AppG1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180928232108_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AppG1.Models.Consulta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("data");

                    b.Property<bool>("finalizado");

                    b.Property<int>("pacienteId");

                    b.Property<string>("resumo");

                    b.Property<bool>("revisao");

                    b.Property<decimal>("valor");

                    b.HasKey("id");

                    b.HasIndex("pacienteId");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("AppG1.Models.Convenio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("codigo");

                    b.Property<string>("descricao");

                    b.HasKey("id");

                    b.ToTable("Convenio");
                });

            modelBuilder.Entity("AppG1.Models.Paciente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("convenioid");

                    b.Property<DateTime>("data_nascimento");

                    b.Property<List<string>>("emails");

                    b.Property<string>("nome");

                    b.Property<bool>("particular");

                    b.Property<List<string>>("telefones");

                    b.HasKey("id");

                    b.HasIndex("convenioid");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("AppG1.Models.Consulta", b =>
                {
                    b.HasOne("AppG1.Models.Paciente", "paciente")
                        .WithMany("consultas")
                        .HasForeignKey("pacienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AppG1.Models.Paciente", b =>
                {
                    b.HasOne("AppG1.Models.Convenio", "convenio")
                        .WithMany("pacientes")
                        .HasForeignKey("convenioid");
                });
#pragma warning restore 612, 618
        }
    }
}
