// <auto-generated />
using System;
using AppChamados.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AppChamados.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180922004025_Add migrations with situacoes")]
    partial class Addmigrationswithsituacoes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AppChamados.Models.Chamados", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataSolucao");

                    b.Property<DateTime>("horaFim");

                    b.Property<DateTime>("horaInicio");

                    b.Property<string>("numero");

                    b.Property<string>("problema");

                    b.Property<int>("situacaoId");

                    b.Property<int>("solicitanteId");

                    b.HasKey("id");

                    b.HasIndex("situacaoId");

                    b.HasIndex("solicitanteId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("AppChamados.Models.Situacoes", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao");

                    b.HasKey("id");

                    b.ToTable("Situacoes");
                });

            modelBuilder.Entity("AppChamados.Models.Solicitante", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("nome");

                    b.Property<string>("telefone");

                    b.HasKey("id");

                    b.ToTable("Solicitante");
                });

            modelBuilder.Entity("AppChamados.Models.Chamados", b =>
                {
                    b.HasOne("AppChamados.Models.Situacoes", "situacao")
                        .WithMany("chamados")
                        .HasForeignKey("situacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AppChamados.Models.Solicitante", "solicitante")
                        .WithMany("chamados")
                        .HasForeignKey("solicitanteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
