// <auto-generated />
using System;
using System.Collections.Generic;
using Associados.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Associados.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Associados.Domain.Associado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cidade")
                        .IsRequired();

                    b.Property<string>("cpf")
                        .IsRequired();

                    b.Property<DateTime>("dataCadastro");

                    b.Property<DateTime>("dataNascimento");

                    b.Property<List<string>>("email");

                    b.Property<string>("endereco");

                    b.Property<int>("estadoCivil");

                    b.Property<string>("nome")
                        .IsRequired();

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("id");

                    b.ToTable("Associados");
                });

            modelBuilder.Entity("Associados.Domain.Dependente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("associadoid");

                    b.Property<DateTime>("dataNascimento");

                    b.Property<string>("grauParentesco");

                    b.Property<string>("nome")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("associadoid");

                    b.ToTable("Dependentes");
                });

            modelBuilder.Entity("Associados.Domain.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("senha")
                        .IsRequired();

                    b.Property<string>("usuario")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Associados.Domain.Dependente", b =>
                {
                    b.HasOne("Associados.Domain.Associado", "associado")
                        .WithMany("dependentes")
                        .HasForeignKey("associadoid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
